# Generated by Django 3.1.4 on 2021-01-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20210103_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Stickers'), ('P', 'Prints'), ('A', 'Aparrel'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
